# Basic options
title: MS 582 Science Website
author: Dr. Weber
email: jweber@ms582.org
description: A website for students of MS 582
twitter_username: BioTeacherNYC
github_username:  BioTeacherNYC

# Build settings
markdown: kramdown
theme: minima
